### ISSUE TITLE
Issues with labels and some symbols

### ISSUE THREAD

**Issue by pierrethiriet** [NieuwlandGeo/SLDReader#68]
I am currently working on a project including _SLDReader_ that helps us a lot for managing layer style in a very easy way.
We developed the project with _0.1.2_ but we got **issues** while upgrading to the version _0.2.4_.

- For point layers with labels (based on properties), the **label** and the **layers** are **not displayed** returning the following error:
```
TypeError: text.split is not a function3 Executor.js:183:23
    createLabel Executor.js:183
    drawLabelWithPointPlacement_ Executor.js:477
    execute_ Executor.js:650
    execute Executor.js:887
    execute ExecutorGroup.js:315
    renderFrame VectorTileLayer.js:504
    render Layer.js:220
    renderFrame Composite.js:112
    renderFrame_ PluggableMap.js:1245
    animationDelay_ PluggableMap.js:185
    <anonyme> self-hosted:875
```
However, labels are displayed for polygons layer.

- For _some_ layers (not all) the layer properties are not used for the style (color for ex.). The layers are uniformly rendered. I didn’t get any error and it is difficult to understand the potential reasons or differences with other layers that are working.  It was working smoothly with the version 0.1.2

- In the _0.1.2_ it was possible to insert space / line break in label for ex.:
```
  <ogc:PropertyName>name</ogc:PropertyName><![CDATA[
]]>(<ogc:PropertyName>pop</ogc:PropertyName><![CDATA[ ]]>inhab.)
```
It is not working anymore in the last version.

So we end up by rolling back to the 0.1.2. 
Thanks.

**Comment by pierrethiriet** [comment]
I just did some test to check if my data was not the problem. I used the sample data from [SLD Cookbook](https://docs.geoserver.org/stable/en/user/styling/sld/cookbook/index.html).
I just tested the point cases. The sample point contains _name_ (string) and _pop_ (int) fields.

With the version *0.2.4*:
The problem seems to be related to the **type of data** used. With the *name* field the label work well while with the *pop*, an integer, the layer is not loaded and an error message is sent (*text.split* is not a function). When converting the *pop* in text the label is working well.

It seems that the problem is the same with polygon, but I have not done any extensive check.

**Comment by ajkopinga** [comment]
I could reproduce the text symbolizer issues. I will fix these.

Regarding your second point
> For some layers (not all) the layer properties are not used for the style (color for ex.).
There have been three major code refactorings between 0.1.2 and 0.2.4, so it's hard for me to say what could have caused this. Can you give me a simplified example SLD + data that exhibits this problem?

**Comment by pierrethiriet** [comment]
I did deeper test with the following _GeoJson_:
```
{
"type": "FeatureCollection",
"name": "census_4326_sub",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
    { "type": "Feature", "properties": { "census_id": "FR246_45046", "pop": 1120, "pop_density": 91.99 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 1.81, 47.97 ], [ 1.77, 47.96 ], [ 1.77, 47.96 ], [ 1.76, 47.97 ], [ 1.74, 47.96 ], [ 1.73, 47.98 ], [ 1.74, 47.99 ], [ 1.76, 47.98 ], [ 1.8, 47.99 ], [ 1.81, 47.99 ], [ 1.81, 47.99 ], [ 1.81, 47.97 ] ] ] ] } },
    { "type": "Feature", "properties": { "census_id": "FR246_45055", "pop": 540, "pop_density": 42.31 }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 1.77, 48.03 ], [ 1.77, 48.02 ], [ 1.78, 48.02 ], [ 1.8, 48.0 ], [ 1.81, 47.99 ], [ 1.8, 47.99 ], [ 1.76, 47.98 ], [ 1.74, 47.99 ], [ 1.77, 48.0 ], [ 1.76, 48.03 ], [ 1.76, 48.04 ], [ 1.77, 48.03 ] ] ] ] } }
  ]
}
```

And the SLD file:
```
        <Rule>
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <PropertyIsLessThanOrEqualTo>
              <ogc:PropertyName>pop_density</ogc:PropertyName>
              <ogc:Literal>50</ogc:Literal>
            </PropertyIsLessThanOrEqualTo>
          </ogc:Filter>
          <PolygonSymbolizer>
            <Fill>
              <se:SvgParameter name="fill">#e5f5f9</se:SvgParameter>
            </Fill>
          </PolygonSymbolizer>
        </Rule>
		
        <Rule>
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <PropertyIsGreaterThanOrEqualTo>
              <ogc:PropertyName>pop_density</ogc:PropertyName>
              <ogc:Literal>50</ogc:Literal>
            </PropertyIsGreaterThanOrEqualTo>
          </ogc:Filter>
          <PolygonSymbolizer>
            <Fill>
              <se:SvgParameter name="fill">#2ca25f</se:SvgParameter>
            </Fill>
          </PolygonSymbolizer>
        </Rule>
```
The results are the following
- _@0.1.2_, _@0.2.0_, _@0.2.1_, _@0.2.2_  : **working**
- **@0.2.3** and  **@0.2.4**:  **Not working** : the layer is styled with a single color (the oneof the heighest category).

**Comment by ajkopinga** [comment]
Thanks for the simple test case!
That makes it easier for me to find out what's going on.

**Comment by ajkopinga** [comment]
I've fixed the labeling issues and I've found the problem with the polygon styles not being applied. Since version 0.2.3, SLDReader cares more about correct namespacing of xml elements. In your filter elements, the `ogc:` prefix is missing from the `PropertyIs(Greater/Less)ThanOrEqualTo` elements. Adding these prefixes should fix the problem.

**Comment by pierrethiriet** [comment]
Thanks a lot. To be honest, the _namespacing_ remain obscure for me. I should do more research on that matter.
Similarly, I still don't know if I should use `svgParameter` or  `cssParameter` , but both seem to do the job...

**Comment by ajkopinga** [comment]
XML namespacing can be a headache when writing SLD by hand, but as a rule of thumb, a Filter element all elements inside live in the ogc namespace and should get an ogc: prefix.

For style attributes, svgParameter is the one to use when writing a v1.1.0 SLD. CssParameter is v1.0.0. The SLDReader is not very strict and allows both cssParameter and svgParameter as style attributes in order to support reading both v1.0.0 and v1.1.0 SLD documents.

**Comment by pierrethiriet** [comment]
Thanks a lot for this information. I'll stick then to _svgParameter_. I guess QGIS is doing a good job when exporting the _SLD_ file but I did found after some experiment that writing by hand was somehow faster and cleaner. I might be wrong on that.
